MFC r227183,r229905,r250432,r250451,r250882:
	- Add missing static keywords to split(1)

	- Fix warning when compiling with gcc46:
	 error: variable 'defname' set but not use

	- Implement 'split -d' which allows a numeric suffix instead of an
	alphabetic one.

	- Bump .Dd for recent content change.
	Avoid signed overflow in error handling code.

PR:		bin/116209